version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: monthly
    assignees: [swsnr]
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: monthly
    assignees: [swsnr]
    ignore:
      - update-types: ["version-update:semver-patch"]
