
# cargo-vet audits file

[[audits.errno]]
who = "Sebastian Wiesner <sebastian@swsnr.de>"
criteria = "safe-to-deploy"
delta = "0.3.3 -> 0.3.9"
notes = "Changes to unsafe code seem sound; mutable buffer is passed with appropriate buffer length."

[[audits.log]]
who = "Sebastian Wiesner <sebastian@swsnr.de>"
criteria = "safe-to-deploy"
delta = "0.4.25 -> 0.4.26"
notes = "Trivial code changes only"

[[audits.retry]]
who = "Sebastian Wiesner <sebastian@swsnr.de>"
criteria = "safe-to-run"
version = "2.0.0"

[[audits.serde]]
who = "Sebastian Wiesner <sebastian@swsnr.de>"
criteria = "safe-to-deploy"
delta = "1.0.217 -> 1.0.218"
notes = "No actual code changes"

[[audits.serde_derive]]
who = "Sebastian Wiesner <sebastian@swsnr.de>"
criteria = "safe-to-deploy"
delta = "1.0.217 -> 1.0.218"
notes = "No code changes"
