name: Release

on:
  push:
    tags: v*

permissions: read-all

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      CARGO_REGISTRY_TOKEN: '${{ secrets.CARGO_REGISTRY_TOKEN }}'
    steps:
      - uses: actions/checkout@v4
      - run: cargo publish --no-verify
