name: Test

on:
  push:
    # Don't build tags; that's redundant with pushes to main normally.
    tags-ignore: "*"
    # Only build main, for all other branches rely on pull requests.  This
    # avoids duplicate builds for pull requests.
    branches: main
    # Don't build for trivial changes
    paths-ignore:
      - "*.md"
      - "LICENSE*"
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Test against MRSV and stable
        rust: ["1.66.0", "stable"]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
      - run: cargo build --all-targets --locked
      - run: cargo test --locked

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy,rustfmt
      - run: cargo clippy --all-targets --locked
      - run: cargo fmt -- --check
      - run: cargo doc
      - uses: EmbarkStudios/cargo-deny-action@v2
      - uses: obi1kenobi/cargo-semver-checks-action@v2

  # See https://mozilla.github.io/cargo-vet/configuring-ci.html
  cargo-vet:
    name: Vet Dependencies
    runs-on: ubuntu-latest
    env:
      CARGO_VET_VERSION: 0.10.0
      # Only consider Linux dependencies, as that's all I care for.
      # Seems to be unofficial, see https://github.com/mozilla/cargo-vet/issues/579, but works
      CARGO_BUILD_TARGET: x86_64-unknown-linux-gnu
    steps:
      - uses: actions/checkout@master
      - uses: dtolnay/rust-toolchain@stable
      - uses: actions/cache@v4
        with:
          path: ${{ runner.tool_cache }}/cargo-vet
          key: cargo-vet-bin-${{ env.CARGO_VET_VERSION }}
      - run: echo "${{ runner.tool_cache }}/cargo-vet/bin" >> $GITHUB_PATH
      - run: cargo install --root ${{ runner.tool_cache }}/cargo-vet --version ${{ env.CARGO_VET_VERSION }} cargo-vet
      - run: cargo vet --locked
